- name: install apt-transport-https
  apt:
    name: apt-transport-https
  
- name: install ca-certificate
  apt:
    name: ca-certificates

- name: install curl
  apt:
    name: curl

- name: install gnupg-agent
  apt:
    name: gnupg-agent

- name: install lsb-core
  apt:
    name: lsb-core
    