- name: add docker apt-key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
  tags: docker

- name: Work out the distribution
  command: lsb_release -cs
  register: lsb_current
  tags: docker

- name: check arch
  command: lsb_release -cs
  register: arch_type
  tags: docker

- name: add docker repo
  apt_repository:
    repo: deb [arch={{arch_type}}] https://download.docker.com/linux/ubuntu {{ lsb_current.stdout }} stable
  tags: docker

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  tags: docker

- name: install docker-ce
  apt:
    name: docker-ce
  tags: docker

- name: install docker-ce-cli
  apt:
    name: docker-ce-cli
  tags: docker

- name: install containerd.io
  apt:
    name: containerd.io
  tags: docker

- name: install docker-compose
  remote_user: "{{ process_execution_user.name }}"
  get_url:
    url: https://github.com/docker/compose/releases/download/1.28.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '+X'
  tags: docker

- name: Add process user to docker groups
  user:
    name: "{{ process_execution_user.name }}"
    shell: /bin/bash
    groups: [docker]
    append: yes
  tags: docker

- name: Run and enable docker
  service:
    name: docker
    state: started
  tags: docker